// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"blog-api/internal/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPostRepositoryInterface creates a new instance of MockPostRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostRepositoryInterface {
	mock := &MockPostRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostRepositoryInterface is an autogenerated mock type for the PostRepositoryInterface type
type MockPostRepositoryInterface struct {
	mock.Mock
}

type MockPostRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostRepositoryInterface) EXPECT() *MockPostRepositoryInterface_Expecter {
	return &MockPostRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockPostRepositoryInterface
func (_mock *MockPostRepositoryInterface) Create(ctx context.Context, post *models.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPostRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - post *models.Post
func (_e *MockPostRepositoryInterface_Expecter) Create(ctx interface{}, post interface{}) *MockPostRepositoryInterface_Create_Call {
	return &MockPostRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, post)}
}

func (_c *MockPostRepositoryInterface_Create_Call) Run(run func(ctx context.Context, post *models.Post)) *MockPostRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Post
		if args[1] != nil {
			arg1 = args[1].(*models.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryInterface_Create_Call) Return(err error) *MockPostRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, post *models.Post) error) *MockPostRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockPostRepositoryInterface
func (_mock *MockPostRepositoryInterface) Delete(ctx context.Context, id uint) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockPostRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPostRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockPostRepositoryInterface_Delete_Call {
	return &MockPostRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockPostRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockPostRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryInterface_Delete_Call) Return(err error) *MockPostRepositoryInterface_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryInterface_Delete_Call) RunAndReturn(run func(ctx context.Context, id uint) error) *MockPostRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function for the type MockPostRepositoryInterface
func (_mock *MockPostRepositoryInterface) FindAll(ctx context.Context, page int, limit int) ([]models.Post, int64, error) {
	ret := _mock.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []models.Post
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]models.Post, int64, error)); ok {
		return returnFunc(ctx, page, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []models.Post); ok {
		r0 = returnFunc(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = returnFunc(ctx, page, limit)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = returnFunc(ctx, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPostRepositoryInterface_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockPostRepositoryInterface_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
func (_e *MockPostRepositoryInterface_Expecter) FindAll(ctx interface{}, page interface{}, limit interface{}) *MockPostRepositoryInterface_FindAll_Call {
	return &MockPostRepositoryInterface_FindAll_Call{Call: _e.mock.On("FindAll", ctx, page, limit)}
}

func (_c *MockPostRepositoryInterface_FindAll_Call) Run(run func(ctx context.Context, page int, limit int)) *MockPostRepositoryInterface_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPostRepositoryInterface_FindAll_Call) Return(posts []models.Post, n int64, err error) *MockPostRepositoryInterface_FindAll_Call {
	_c.Call.Return(posts, n, err)
	return _c
}

func (_c *MockPostRepositoryInterface_FindAll_Call) RunAndReturn(run func(ctx context.Context, page int, limit int) ([]models.Post, int64, error)) *MockPostRepositoryInterface_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAuthorID provides a mock function for the type MockPostRepositoryInterface
func (_mock *MockPostRepositoryInterface) FindByAuthorID(ctx context.Context, authorID uint) ([]models.Post, error) {
	ret := _mock.Called(ctx, authorID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAuthorID")
	}

	var r0 []models.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]models.Post, error)); ok {
		return returnFunc(ctx, authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []models.Post); ok {
		r0 = returnFunc(ctx, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepositoryInterface_FindByAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAuthorID'
type MockPostRepositoryInterface_FindByAuthorID_Call struct {
	*mock.Call
}

// FindByAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID uint
func (_e *MockPostRepositoryInterface_Expecter) FindByAuthorID(ctx interface{}, authorID interface{}) *MockPostRepositoryInterface_FindByAuthorID_Call {
	return &MockPostRepositoryInterface_FindByAuthorID_Call{Call: _e.mock.On("FindByAuthorID", ctx, authorID)}
}

func (_c *MockPostRepositoryInterface_FindByAuthorID_Call) Run(run func(ctx context.Context, authorID uint)) *MockPostRepositoryInterface_FindByAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryInterface_FindByAuthorID_Call) Return(posts []models.Post, err error) *MockPostRepositoryInterface_FindByAuthorID_Call {
	_c.Call.Return(posts, err)
	return _c
}

func (_c *MockPostRepositoryInterface_FindByAuthorID_Call) RunAndReturn(run func(ctx context.Context, authorID uint) ([]models.Post, error)) *MockPostRepositoryInterface_FindByAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockPostRepositoryInterface
func (_mock *MockPostRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.Post, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Post
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.Post, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.Post); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Post)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPostRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPostRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPostRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockPostRepositoryInterface_FindByID_Call {
	return &MockPostRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPostRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockPostRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryInterface_FindByID_Call) Return(post *models.Post, err error) *MockPostRepositoryInterface_FindByID_Call {
	_c.Call.Return(post, err)
	return _c
}

func (_c *MockPostRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.Post, error)) *MockPostRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockPostRepositoryInterface
func (_mock *MockPostRepositoryInterface) Update(ctx context.Context, post *models.Post) error {
	ret := _mock.Called(ctx, post)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.Post) error); ok {
		r0 = returnFunc(ctx, post)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPostRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockPostRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - post *models.Post
func (_e *MockPostRepositoryInterface_Expecter) Update(ctx interface{}, post interface{}) *MockPostRepositoryInterface_Update_Call {
	return &MockPostRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, post)}
}

func (_c *MockPostRepositoryInterface_Update_Call) Run(run func(ctx context.Context, post *models.Post)) *MockPostRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.Post
		if args[1] != nil {
			arg1 = args[1].(*models.Post)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPostRepositoryInterface_Update_Call) Return(err error) *MockPostRepositoryInterface_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPostRepositoryInterface_Update_Call) RunAndReturn(run func(ctx context.Context, post *models.Post) error) *MockPostRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}
