// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"blog-api/internal/models"
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepositoryInterface creates a new instance of MockUserRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepositoryInterface {
	mock := &MockUserRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepositoryInterface is an autogenerated mock type for the UserRepositoryInterface type
type MockUserRepositoryInterface struct {
	mock.Mock
}

type MockUserRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepositoryInterface) EXPECT() *MockUserRepositoryInterface_Expecter {
	return &MockUserRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) Create(ctx context.Context, user *models.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockUserRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *MockUserRepositoryInterface_Expecter) Create(ctx interface{}, user interface{}) *MockUserRepositoryInterface_Create_Call {
	return &MockUserRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *MockUserRepositoryInterface_Create_Call) Run(run func(ctx context.Context, user *models.User)) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) Return(err error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepositoryInterface_Create_Call) RunAndReturn(run func(ctx context.Context, user *models.User) error) *MockUserRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByUsername provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) ExistsByUsername(ctx context.Context, username string) (bool, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByUsername")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_ExistsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByUsername'
type MockUserRepositoryInterface_ExistsByUsername_Call struct {
	*mock.Call
}

// ExistsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepositoryInterface_Expecter) ExistsByUsername(ctx interface{}, username interface{}) *MockUserRepositoryInterface_ExistsByUsername_Call {
	return &MockUserRepositoryInterface_ExistsByUsername_Call{Call: _e.mock.On("ExistsByUsername", ctx, username)}
}

func (_c *MockUserRepositoryInterface_ExistsByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepositoryInterface_ExistsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_ExistsByUsername_Call) Return(b bool, err error) *MockUserRepositoryInterface_ExistsByUsername_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepositoryInterface_ExistsByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (bool, error)) *MockUserRepositoryInterface_ExistsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) FindByID(ctx context.Context, id uint) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockUserRepositoryInterface_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockUserRepositoryInterface_Expecter) FindByID(ctx interface{}, id interface{}) *MockUserRepositoryInterface_FindByID_Call {
	return &MockUserRepositoryInterface_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockUserRepositoryInterface_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByID_Call) Return(user *models.User, err error) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uint) (*models.User, error)) *MockUserRepositoryInterface_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUsername provides a mock function for the type MockUserRepositoryInterface
func (_mock *MockUserRepositoryInterface) FindByUsername(ctx context.Context, username string) (*models.User, error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for FindByUsername")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepositoryInterface_FindByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUsername'
type MockUserRepositoryInterface_FindByUsername_Call struct {
	*mock.Call
}

// FindByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepositoryInterface_Expecter) FindByUsername(ctx interface{}, username interface{}) *MockUserRepositoryInterface_FindByUsername_Call {
	return &MockUserRepositoryInterface_FindByUsername_Call{Call: _e.mock.On("FindByUsername", ctx, username)}
}

func (_c *MockUserRepositoryInterface_FindByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepositoryInterface_FindByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepositoryInterface_FindByUsername_Call) Return(user *models.User, err error) *MockUserRepositoryInterface_FindByUsername_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepositoryInterface_FindByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (*models.User, error)) *MockUserRepositoryInterface_FindByUsername_Call {
	_c.Call.Return(run)
	return _c
}
